name: pipeline-check
on: [push, workflow_call]
jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: nexientdevops/platform-images
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nexient-llc/.github/actions/pre-merge@main
